Used command

diff --git a/plays/join-kubernetes-workers.yaml b/plays/join-kubernetes-workers.yaml
--- a/plays/join-kubernetes-workers.yaml
+++ b/plays/join-kubernetes-workers.yaml
@@ -15,13 +15,17 @@
     - name: Add k3s node
       ansible.builtin.shell: |
         curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="agent --server https://{{ groups['kubernetesMasterNodes'][0] }}:6443 --token {{ kubernetes.k3s_token }}" sh -s -
-      
       become: true
       when: node_is_in_cluster.stdout == "false"
       
     - name: Taint node
       ansible.builtin.shell: |
-        kubectl taint node $(kubectl get nodes --no-headers | awk '{print $1}' | grep {{ inventory_hostname }}) {{ item.key }}:{{ item.effect }} --overwrite
+        NODE_NAME=$(kubectl get nodes --no-headers | awk '{print $1}' | grep k8s.worker01) && \
+        if [ -n "$NODE_NAME" ]; then \
+          kubectl taint node ${NODE_NAME} {{ item.key }}:{{ item.effect }} --overwrite \
+        else 
+          echo "Node k8s.worker01 not found"; \
+          exit 1; \
       loop: "{{ hostvars[inventory_hostname].taints }}"
       when: hostvars[inventory_hostname].taints is defined
-      delegate_to: alteret.master01
+      delegate_to: "{{ groups['kubernetesMasterNodes'][0] }}"
